name: PR release → main

on:
  push:
    branches:
      - 'release/**'

jobs:
  pr-release-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: Create PR to main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head ${{ github.ref_name }} \
            --title "${{ github.ref_name }} → main" \
            --body "PR automático da branch de release para main."
